// words.js
export const wordList = [
    "constitution",
    "democracy",
    "republic",
    "freedom",
    "justice",
    "equality",
    "sovereignty",
    "legislation",
    "fundamental",
    "amendment",
    "Republic",
    "Democracy",
    "Fundamental Rights",
    "Judiciary",
    "Parliament",
    "President",
    "Prime Minister",
    "Law",
    "Governance",
    "Union",
    "States",
    "Fundamental Duties",
    "Secularism",
    "Preamble",
    "Article",
    "Amendments",
    "Citizenship",
    "Satyagraha",
    "Judiciary",
    "Election",
    "Legislation",
    "Federalism",
    "Legislature",
    "Supreme Court",
    "High Court",
    "Advocate",
    "Petition",
    "Habeas Corpus",
    "Equality",
    "Social Justice",
    "Assembly",
    "Cabinet",
    "Power",
    "Autonomy",
    "Bill",
    "Constitutionalism",
    "Dr. B.R. Ambedkar",
    "Lok Sabha",
    "Rajya Sabha",
    "Lok Sabha Elections",
    "Rajya Sabha Elections",
    "President's Rule",
    "Emergency",
    "Unity in Diversity",
    "Anti-defection",
    "Uniform Civil Code",
    "Political Parties",
    "Coalition",
    "Reservation",
    "Scheduled Castes",
    "Scheduled Tribes",
    "Backward Classes",
    "Caste System",
    "Commission",
    "National Security",
    "Welfare State",
    "Parliament Act",
    "State Legislature",
    "Governors",
    "Chief Justice",
    "Law Commission",
    "Legal Framework",
    "Election Commission",
    "Cabinet Ministers",
    "Judicial Review",
    "Civil Liberties",
    "National Integration",
    "Right to Life",
    "Article 370",
    "Article 35A",
    "Right to Information",
    "Right to Education",
    "Fundamental Right to Privacy",
    "Right to Property",
    "Right to Freedom",
    "Constitutional Court",
    "Bureaucracy",
    "CBI",
    "Lokpal",
    "National Commission",
    "Judicial Independence",
    "Public Administration",
    "Supreme Law",
    "Articles of the Constitution",
    "State Council",
    "National Anthem",
    "National Flag",
    "National Symbols",
    "Schedules",
    "President of India",
    "Union Territories",
    "National Identity",
    "Indian Parliament",
    "Human Rights",
    "Right to Assembly",
    "Economic Justice",
    "Social Rights",
    "Political Rights",
    "Civil Rights",
    "Local Governance",
    "Panchayati Raj",
    "Gram Sabha",
    "Statehood",
    "Administrative Divisions",
    "National Policy",
    "Sovereign State",
    "Fundamental Duties",
    "Parliamentary Sovereignty",
    "Concurrent List",
    "Union List",
    "State List",
    "Taxation",
    "Finance Commission",
    "GST",
    "Fiscal Policy",
    "Public Sector",
    "Private Sector",
    "National Bank",
    "Reserve Bank of India",
    "Currency",
    "Economy",
    "Public Debt",
    "Social Security",
    "Armed Forces",
    "National Security Act",
    "Border Security Force",
    "National Disaster Management",
    "Cyber Laws",
    "RTI Act",
    "Environmental Laws",
    "Anti-corruption",
    "Lok Sabha",
    "Rajya Sabha",
    "Legislative Assembly",
    "Legislative Council",
    "Legal Aid",
    "Right to Equality",
    "Freedom",
    "Religious Freedom",
    "Racial Equality",
    "Secular State",
    "Secular Laws",
    "Anti-untouchability Laws",
    "Rights",
    "Right to Vote",
    "Education Ministry",
    "Defence Ministry"
  ];
  