// words.js
export const wordList = [
    "constitution",
    "democracy",
    "republic",
    "freedom",
    "justice",
    "equality",
    "sovereignty",
    "legislation",
    "fundamental",
    "amendment",
    "Republic",
    "Democracy",
    "Fundamental Rights",
    "Directive Principles",
    "Judiciary",
    "Parliament",
    "President",
    "Prime Minister",
    "Law",
    "Governance",
    "Union",
    "States",
    "Fundamental Duties",
    "Secularism",
    "Preamble",
    "Article",
    "Amendments",
    "Citizenship",
    "Satyagraha",
    "Judiciary Review",
    "Election",
    "Legislation",
    "Federalism",
    "Legislature",
    "Supreme Court",
    "High Court",
    "Advocate",
    "Petition",
    "Habeas Corpus",
    "Public Interest Litigation",
    "Fundamental Rights Enforcement",
    "Equality",
    "Social Justice",
    "Assembly",
    "Cabinet",
    "Legislature's Role",
    "Separation of Powers",
    "Autonomy",
    "Bill",
    "Constitutionalism",
    "Indira Gandhi",
    "Jawaharlal Nehru",
    "Dr. B.R. Ambedkar",
    "Lok Sabha",
    "Rajya Sabha",
    "Lok Sabha Elections",
    "Rajya Sabha Elections",
    "President's Rule",
    "Emergency",
    "Unity in Diversity",
    "Anti-defection",
    "Uniform Civil Code",
    "Political Parties",
    "Coalition",
    "Reservation",
    "Scheduled Castes",
    "Scheduled Tribes",
    "Backward Classes",
    "Caste System",
    "Mandal Commission",
    "National Security",
    "Welfare State",
    "Parliament Act",
    "State Legislature",
    "Bicameral",
    "Unicameral",
    "Governors",
    "Chief Justice",
    "Law Commission",
    "Legal Framework",
    "Election Commission",
    "Cabinet Ministers",
    "Deputy Prime Minister",
    "Parliamentary Democracy",
    "Constitution Assembly",
    "Judicial Review",
    "Civil Liberties",
    "National Integration",
    "Right to Life",
    "Article 370",
    "Article 35A",
    "Right to Information",
    "Right to Education",
    "Fundamental Right to Privacy",
    "Right to Property",
    "Right to Freedom",
    "Constitutional Court",
    "Bureaucracy",
    "CBI",
    "Lokpal",
    "National Commission",
    "Judicial Independence",
    "Public Administration",
    "Supreme Law",
    "Articles of the Constitution",
    "State Council",
    "National Anthem",
    "National Flag",
    "National Symbols",
    "Schedules",
    "President of India",
    "Union Territories",
    "National Identity",
    "Indian Parliament",
    "Human Rights",
    "Right to Assembly",
    "Economic Justice",
    "Social Rights",
    "Political Rights",
    "Civil Rights",
    "Local Governance",
    "Panchayati Raj",
    "Gram Sabha",
    "Statehood",
    "Administrative Divisions",
    "National Policy",
    "Sovereign State",
    "Fundamental Duties",
    "Parliamentary Sovereignty",
    "Concurrent List",
    "Union List",
    "State List",
    "Taxation",
    "Finance Commission",
    "GST",
    "Fiscal Policy",
    "Public Sector",
    "Private Sector",
    "National Bank",
    "Reserve Bank of India",
    "Currency",
    "Economy",
    "Public Debt",
    "Social Security",
    "Armed Forces",
    "National Security Act",
    "Border Security Force",
    "National Disaster Management",
    "Cyber Laws",
    "RTI Act",
    "Environmental Laws",
    "Anti-corruption",
    "Lok Sabha Speaker",
    "Rajya Sabha Speaker",
    "Legislative Assembly",
    "Legislative Council",
    "Constitutional Amendments",
    "Legal Aid",
    "Right to Equality",
    "Right to Freedom of Speech",
    "Protection of Minorities",
    "Religious Freedom",
    "Racial Equality",
    "Secular State",
    "Secular Laws",
    "Anti-untouchability Laws",
    "Child Rights",
    "Women's Rights",
    "Right to Vote",
    "Electoral College",
    "Electoral Reforms",
    "Voter Registration",
    "Political Party Systems",
    "Nationalism",
    "National Emergency",
    "Public Health",
    "Child Labor Laws",
    "International Relations",
    "Foreign Policy",
    "Human Development Index",
    "Cultural Rights",
    "Linguistic Rights",
    "Constitution of India",
    "Civil Services",
    "Political Science",
    "National Congress",
    "Muslim League",
    "RSS",
    "Ambedkar",
    "Gandhi",
    "Partition",
    "Indian National Movement",
    "Federation",
    "Individual Rights",
    "Laws of War",
    "Welfare Schemes",
    "Minorities Welfare",
    "Rural Development",
    "Urban Development",
    "Foreign Direct Investment",
    "Border Issues",
    "Humanitarian Laws",
    "Public Health Policies",
    "Rural Development Ministry",
    "Education Ministry",
    "Defence Ministry"
  ];
  